// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

module.exports = {
    api: {
        invokeUrl: 'https://a8u27dv6vb.execute-api.us-east-1.amazonaws.com/prod' // e.g. https://rc7nyt4tql.execute-api.us-west-2.amazonaws.com/prod,
    }
}
